![logo_python3](https://www.python.org/static/img/python-logo.png "Logo Python3")
# ``IMPORTACIÓN DE MÓDULOS EN PYTHON``

<BR/>
**``COMO IMPORTAR MÓDULOS``**


``Los módulos son programas que amplían las funciones y clases de Python para realizar tareas específicas.``
``En`` https://docs.python.org/3/py-modindex.html ``se puede encontar el índice de módulos de Python.``

+ ``Por ejemplo, el modulo nos permite usar muchas funciones del sistema operativo.``

``Los módulos se pueden cargar de las siguientes formas:``

   + ``from`` ***modulo*** ``import``
   + ``import`` ***modulo***
   + ``import`` ***modulo*** ``as`` ***alias***


``Dependiendo de cómo hayamos importado el módulo, así tendremos que utilizarlo.``

In [31]:
# Importamos solo la función array del modulo numpy
from numpy import array
a = array( [2,3,4] )       
a

array([2, 3, 4])

In [32]:
# Importamos todo el módulo numpy
import numpy 
a = numpy.array( [2,3,4] )       
a

array([2, 3, 4])

In [33]:
# Importamos el módulo numpy y le asignamos el alias 'np'
# Cuando queramos importar funciones de dicho módulo lo haremos refiriendonos al alias
import numpy as np
# En vez de escribir numpy.array, escribimos np.array
a = np.array( [2,3,4] )
a

array([2, 3, 4])

<br/>
**``OPERACIONES DISPONIBLES DE UNA LIBERÍA``**

In [34]:
# Importamos el módulo math y listamos todas las operaciones disponibles mediante dir()
import math
dir(math)

['__doc__',
 '__loader__',
 '__name__',
 '__package__',
 '__spec__',
 'acos',
 'acosh',
 'asin',
 'asinh',
 'atan',
 'atan2',
 'atanh',
 'ceil',
 'copysign',
 'cos',
 'cosh',
 'degrees',
 'e',
 'erf',
 'erfc',
 'exp',
 'expm1',
 'fabs',
 'factorial',
 'floor',
 'fmod',
 'frexp',
 'fsum',
 'gamma',
 'gcd',
 'hypot',
 'inf',
 'isclose',
 'isfinite',
 'isinf',
 'isnan',
 'ldexp',
 'lgamma',
 'log',
 'log10',
 'log1p',
 'log2',
 'modf',
 'nan',
 'pi',
 'pow',
 'radians',
 'sin',
 'sinh',
 'sqrt',
 'tan',
 'tanh',
 'tau',
 'trunc']

In [35]:
# Dentro del módulo 'math' hay una función llamada 'pow'
# Para acceder a la documentación de la función pow escribimos lo siguiente:
help(pow)

Help on built-in function pow in module builtins:

pow(x, y, z=None, /)
    Equivalent to x**y (with two arguments) or x**y % z (with three arguments)
    
    Some types, such as ints, are able to use a more efficient algorithm when
    invoked using the three argument form.



In [36]:
# Importamos el módulo 'math' como 'mt' y llamamos a la función 'sin' para calcular el seno del número 34
import math as mt
mt.sin(34)

0.5290826861200238

In [37]:
# Llamada a la función 'pi' del módulo 'math'
mt.pi

3.141592653589793

In [38]:
# Llamada a la función raíz cuadradra del módulo 'math'
mt.sqrt(24)
help(mt.sqrt)

Help on built-in function sqrt in module math:

sqrt(...)
    sqrt(x)
    
    Return the square root of x.



``Para listar los módulos que tenemos instalados y que por tanto podemos importar en nuestros programas, basta con ejecutar el siguiente comando:``

In [39]:
!conda list

# packages in environment at C:\ProgramData\Anaconda3:
#
_license                  1.1                      py36_1  
alabaster                 0.7.9                    py36_0  
anaconda                  4.3.1               np111py36_0  
anaconda-client           1.6.0                    py36_0  
anaconda-navigator        1.5.0                    py36_0  
anaconda-project          0.4.1                    py36_0  
astroid                   1.4.9                    py36_0  
astropy                   1.3                 np111py36_0  
babel                     2.3.4                    py36_0  
backports                 1.0                      py36_0  
beautifulsoup4            4.5.3                    py36_0  
bitarray                  0.8.1                    py36_1  
blaze                     0.10.1                   py36_0  
bokeh                     0.12.4                   py36_0  
boto                      2.45.0                   py36_0  
bottleneck                1.2.0            