![logo_python3](https://www.python.org/static/img/python-logo.png "Logo Python3")
## ''Procesar datos usando Arrays''

**``EFICIENCIA DE NumPy``**

``Los arrays realizan una gestión de la memoria mucho más eficiente que las listas y por tanto se mejora el rendimiento.``

+ ``Se realizan muchas operaciones mediante expresiones sobre arrays que en otros casos requerirían múltiples y costosos loops.
A esto se le llama vectorización.``
+ ``Las funciones de NumPy se ejecutan de forma tan eficiente como se ejecutarían en otros lenguajes como por ejemplo Fortran, C y C++.``
+ ``Para los casos en los que la ejecución sea más eficiente en otros lenguajes, como por ejemplo Fortran, existen herramientas que nos permiten ejecutar desde Python nuestros códigos en otros lenguajes como f2py.``

**``EXPRESIONES CONDICIONALES``**

``La función where() es la versión vectorizada de la expresión ternaria x if cond else y que ya hemos visto anteriormente.
Supongamos que tenemos los tres arrays:``

In [15]:
import numpy as np
x = np.arange(1,5)
y = np.arange(5,9)
cond = np.array([True, False, False, True])
x, y

(array([1, 2, 3, 4]), array([5, 6, 7, 8]))

``Supongamos que queremos obtener el valor de x cuando se cumpla la condición en  condcond . En otro caso obtendremos el valor de y. Queremos obtener por tanto el array [1,6,7,4].``

In [16]:
# Primera versión sin operacion vectorizada where
z1 = np.array([x if cond else y for x, y, cond in zip(x, y, cond)])
z1

array([1, 6, 7, 4])

In [17]:
# Segunda versión - operación vectorizada where
x = np.arange(1,5)
y = np.arange(5,9)
cond = np.array([True, False, False, True])
z2 = np.where(cond, x, y)
z2

array([1, 6, 7, 4])

``Los dos últimos argumentos de la operación where no tienen por qué ser arrays, pueden ser escalares.
En análisis de datos la operación where se utiliza mucho para crear nuevos arrays a partir de los datos de otros. Supongamos que tenemos un array  aa  de dos dimensiones y queremos construir otro array  r  tal que:``

r(x,y) = \begin{cases} 1 &\mbox{if } a(x,y) \ge 0 \\
                       -1 & \mbox{if }  a(x,y) \lt 0. \end{cases}

In [18]:
# Array con forma de campana de gauss
a = np.random.randn(3,5)
a

array([[ 0.30200588, -0.96259522, -0.59344362,  0.07480439,  0.45804962],
       [ 0.4783826 ,  0.02332432,  0.68480014, -0.28533685,  1.35706072],
       [ 1.41417884,  0.47809901,  0.34058848,  0.48435847,  1.24260344]])

In [19]:
# Función escalón
r = np.where( a >= 0, 1, -1)
r

array([[ 1, -1, -1,  1,  1],
       [ 1,  1,  1, -1,  1],
       [ 1,  1,  1,  1,  1]])

In [21]:
a = np.random.randn(4,5)
a

array([[-1.1837773 ,  0.57394451, -1.39861664,  0.009056  ,  0.80238162],
       [ 0.60558091,  0.48300309, -0.4513113 , -1.31444623,  1.5669763 ],
       [-0.30030349,  0.73186563, -0.8100717 ,  0.31537371,  1.00358801],
       [-0.60765749,  1.06326293,  1.53742979, -0.47360166, -0.07565701]])

In [22]:
( a > 0 )

array([[False,  True, False,  True,  True],
       [ True,  True, False, False,  True],
       [False,  True, False,  True,  True],
       [False,  True,  True, False, False]], dtype=bool)

In [23]:
(a > 0).sum()

11